[package]
name = "april_tags"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
lto = true

[dependencies]
